In [9]:
!pip install numpy

     -------------------------------------- 14.7/14.7 MB 942.1 kB/s eta 0:00:00


You should consider upgrading via the 'C:\Users\yassi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.


In [10]:
from numpy import matrix
from typing import List

In [2]:
class Edge:
    def __init__(self, target, weight):
        self.target = target
        self.weight = weight
    
    def __repr__(self):
        return f"Edge(target={self.target}, weight={self.weight})"

In [3]:
class Vertex:
    def __init__(self, data: str, next: List[Edge] = None):
        self.data = data
        self.next = next if next else []

    def add_edge(self, target: str, weight: int):
        self.next.append(Edge(target, weight))

    def __repr__(self):
        return f"Vertex(data={self.data}, next={self.next})"

In [6]:
class Graph:
    def __init__(self, vertices: List[Vertex] = None):
        self.vertices = vertices if vertices else []

    def add_vertex(self, vertex: Vertex):
        self.vertices.append(vertex)

    def get_vertex(self, data: str):
        for vertex in self.vertices:
            if vertex.data == data:
                return vertex
        return

    def add_edge(self, source: str, target: str, weight: int):
        self.get_vertex(source).add_edge(target, weight)

    def get_adjacency_list(self):
        adjacency_list = {}
        for vertex in self.vertices:
            adjacency_list[vertex.data] = [(edge.target,edge.weight) for edge in vertex.next]
        return adjacency_list

    def get_adjacency_matrix(self):
        adjacency_matrix = []
        for vertex in self.vertices:
            adjacency_matrix.append([0] * len(self.vertices))
        for i, vertex in enumerate(self.vertices):
            for edge in vertex.next:
                adjacency_matrix[i][self.vertices.index(self.get_vertex(edge.target))] = edge.weight
        return adjacency_matrix

    def __repr__(self):
        return f"Graph(vertices={self.vertices})"

In [12]:
graph = Graph()

vertices = [Vertex('A'), Vertex('B'), Vertex('C'), Vertex('D'), Vertex('E')]

for vertex in vertices:
    graph.add_vertex(vertex)

graph.add_edge('A', 'B', 1)
graph.add_edge('B', 'A', 2)
graph.add_edge('B', 'C', 1)

print(graph.get_adjacency_list())
print()
print(matrix(graph.get_adjacency_matrix()))

{'A': [('B', 1)], 'B': [('A', 2), ('C', 1)], 'C': [], 'D': [], 'E': []}

[[0 1 0 0 0]
 [2 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
