In [1]:
!pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 120.1 MB/s eta 0:00:0000:0100:01
You should consider upgrading via the '/home/gitpod/.pyenv/versions/3.8.13/bin/python3.8 -m pip install --upgrade pip' command.


In [2]:
from numpy import matrix
from typing import List, Tuple

In [3]:
class Edge:
    def __init__(self, origin, target, weight):
        self.origin = origin
        self.target = target
        self.weight = weight
    
    def __repr__(self):
        return f"Edge(origin={self.origin}, target={self.target}, weight={self.weight})"

In [4]:
class Vertex:
    def __init__(self, name: str, next: List[Edge] = None):
        self.name = name
        self.next = next if next else []

    def __repr__(self):
        return f"Vertex(name={self.name}, next={self.next})"

In [5]:
class Graph:
    def __init__(self, vertices: List[Vertex] = None):
        self.vertices = vertices if vertices else []

    def add_vertex(self, vertex: Vertex):
        self.vertices.append(vertex)

    def add_vertices(self, vertices: List[Vertex]):
        for vertex in vertices:
            self.add_vertex(vertex)

    def get_vertex(self, name: str):
        for vertex in self.vertices:
            if vertex.name == name:
                return vertex
        return

    def add_edge(self, edge: Tuple[str, str, int]):
        self.get_vertex(edge[0]).next.append(Edge(*edge))

    def add_edges(self, edges: List[Tuple[str, str, int]]):
        for edge in edges:
            self.add_edge(edge)

    def get_edges(self):
      return [edge for vertex in self.vertices for edge in vertex.next]

    def get_weight(self, origin, target):
      for edge in self.get_edges():
        if edge.origin == origin and edge.target == target:
          return edge.weight
      return 0

    def get_adjacency_list(self):
        adjacency_list = {}
        for vertex in self.vertices:
            adjacency_list[vertex.name] = [(edge.target,edge.weight) for edge in vertex.next]
        return adjacency_list

    def get_adjacency_matrix(self):
        adjacency_matrix = []
        for vertex in self.vertices:
            adjacency_matrix.append([0] * len(self.vertices))
        for i, vertex in enumerate(self.vertices):
            for edge in vertex.next:
                adjacency_matrix[i][self.vertices.index(self.get_vertex(edge.target))] = edge.weight
        return adjacency_matrix

    def __repr__(self):
        return f"Graph(vertices={self.vertices})"

In [6]:
graph = Graph()

graph.add_vertices([Vertex('A'), Vertex('B'), Vertex('C'), Vertex('D'), Vertex('E')])
graph.add_edges([('A', 'B', 1), ('A', 'C', 1), ('B', 'C', 1), ('B', 'D', 1), ('C', 'D', 1), ('D', 'E', 1)])

print(graph.get_adjacency_list())
print()
print(matrix(graph.get_adjacency_matrix()))

{'A': [('B', 1), ('C', 1)], 'B': [('C', 1), ('D', 1)], 'C': [('D', 1)], 'D': [('E', 1)], 'E': []}

[[0 1 1 0 0]
 [0 0 1 1 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]
